### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by LeoBdt** [HimmelKreis4865/BetterNick#5]
hello could you add rainbow argument ? 

example : 

/nick set test rainbow

regards.

**Comment by HimmelKreis4865** [comment]
Yes, I can try, but it's not easy. But very nice oder, that will follow soon!

**Comment by HimmelKreis4865** [comment]
I worked on it today and now it's half-ready. So now, you can make a colored Name *but*:
I can't edit numbers (they have no special color) because of § - colorcodes. 
therefore, the rainbow name consists only of numerous colors such as §0, §1, §2 .... §9 so we have for example no light green, no yellow.
I try to change it but I can not promise anything
